branches:
  only:
    - master

skip_tags: true

os: Windows Server 2012

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0

cache:
  - C:\bin\golo-1.1.0

install:
  - ps: cinst golo -Version 1.1.0
  - cmd: set PATH=%PATH%;C:\bin\golo-1.1.0\bin

build_script:
  - cmd: golo golo --files ModernHeadlineBuilder.golo
